- package.json
- src/LinearChart/components/HoverLines/index.tsx
- yarn.lock
> GDC-818: Поднять версию widgets-configs в widgets

- .storybook/preview.js
- package.json
- src/Roadmap/index.tsx
> GDC-856: Виджеты: Обновить версию @consta/uikit

- src/BackgroundBarChart/index.stories.tsx
- src/BackgroundBarChart/index.tsx
- src/BarChart/index.stories.tsx
- src/BarChart/index.tsx
- src/MultiBarChart/index.stories.tsx
- src/MultiBarChart/index.tsx
- src/SludgeChart/index.tsx
- src/TornadoChart/index.stories.tsx
- src/TornadoChart/index.tsx
- src/_private/components/BarChart/index.tsx
> TSUB-1138: Barchart prop для форматирования значения в тултипе.

- package.json
- yarn.lock
> GDC-909: Виджеты: обновление Jest и TSJest в проекте до 26 версии

- package.json
- src/LinearChart/components/Axis/index.tsx
- yarn.lock
> GDC-1003: @consta/widgets обновить версию конфига

- src/BackgroundBarChart/components/Column/index.tsx
- src/BackgroundBarChart/components/Group/index.tsx
- src/_private/components/BarChart/components/Column/index.tsx
- src/_private/components/BarChart/components/Group/index.tsx
- src/_private/components/BarChart/components/Section/index.tsx
- src/_private/components/BarChart/index.tsx
- src/_private/components/BarChart/renders.tsx
> GDC-765: Горизонтальный барчарт. Неверно выровнен нижний unit

- src/BarChart/__tests__/helpers.test.ts
- src/BarChart/helpers.ts
- src/BarChart/index.tsx
> GDC-760: BarChart. Возможность красить столбцы в разные цвета.

- package.json
- types/global.d.ts
- yarn.lock
https://jira.csssr.io/browse/GDC-1031
- обновил версию конфига
> GDC-1031: Consta-widgets: Добавить @testing-library/jest-dom и обновить jest

- src/BackgroundBarChart/components/Column/index.tsx
- src/BackgroundBarChart/components/Group/index.tsx
- src/_private/components/BarChart/components/Section/index.tsx
> GDC-923: Барчарт с накоплениями. Выводить тултип по центру внутреннего бара

- package.json
> GDC-1097: Обновить версию Consta в виджетах до 1.10.6

- src/BackgroundBarChart/__stories__/index.stories.tsx
- src/BackgroundBarChart/index.tsx
- src/_private/components/BarChart/index.css
- src/_private/components/BarChart/index.tsx
> GDC-922: Барчарт с накоплением. Скролл в графиках.

- docs/ARRANGEMENTS_FOR_CODE_STYLE.mdx
- src/DatePicker/index.tsx
- src/Map/index.tsx
- src/_private/components/BarChart/renders.tsx
> GDC-887: Виджеты: подумать, как предотвратить проблемы с хуками в рендер-пропах БарЧарта

- src/BarChart/index.tsx
- src/MultiBarChart/index.tsx
> GDC-398: Выбрать способ реализации отображения чисел над барами при группировке баров

- src/BarChart/__stories__/index.stories.tsx
- src/BarChart/index.tsx
- src/MultiBarChart/index.stories.tsx
- src/MultiBarChart/index.tsx
- src/TornadoChart/index.stories.tsx
- src/TornadoChart/index.tsx
- src/_private/components/BarChart/index.css
- src/_private/components/BarChart/index.tsx
> GDC-1101: Виджеты. Барчарт. Добавить возможность выводить заголовок, как в линейном графике

- package.json
- src/LinearChart/index.stories.tsx
- src/SludgeChart/index.stories.tsx
- yarn.lock
> GDC-186: Линтер: запретить any

- src/TornadoChart/__stories__/docs.mdx
- src/TornadoChart/__stories__/examples/TornadoChartExample.tsx
- src/TornadoChart/__stories__/index.stories.tsx
- src/TornadoChart/data.mock.ts
Добавляет документацию для TornadoChart.
Помогите с примером использования, плиз.
> GDC-1085: добавить документацию для TornadoChart-а

- package.json
> GDC-688: Разобраться с командой для запуска билда в компонентах

- src/BarChart/__stories__/index.stories.tsx
- src/BarChart/index.tsx
- src/MultiBarChart/index.stories.tsx
- src/MultiBarChart/index.tsx
- src/SludgeChart/index.stories.tsx
- src/SludgeChart/index.tsx
- src/TornadoChart/__stories__/index.stories.tsx
- src/TornadoChart/index.tsx
> GDC-1068: Реализовать скролл во всех барчартах

- package.json
Reverts gazprom-neft/consta-widgets#53
Публикация пакета зависает в GH, задача реопнута
> Revert "GDC-688: Разобраться с командой для запуска билда в компонентах"

- src/LinearChart/components/LineWithDots/index.css
- src/LinearChart/components/LineWithDots/index.tsx
- src/LinearChart/index.stories.tsx
- src/LinearChart/index.tsx
> GDC-1141: Виджеты. Добавить возможность выводить значения точек на линейном графике

- src/_private/storybook/decorators/DocsContainer/index.css
> GDC-1103: Дока: Отображение компонентов в доке искажено

- src/DatePicker/components/Calendar/index.css
- src/Roadmap/components/Line/index.css
> fix gazprom-neft#65
